### ISSUE TITLE
problems for self training

### ISSUE THREAD

**Issue by vickyFox** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#12]
Good job and it helps me a lot! You mentioned you used the self training strategy in the training process. However, I'm confused which stage of the training process you introduce the self-training strategy. Thank you very much!

**Comment by Siyuan-Zhou** [comment]
@vickyFox Self-training is performed after finetuning (mixed). If you want to reproduce our ST results, you may need to perform a secondary finetuning after self-training.

**Comment by vickyFox** [comment]
Thank you for your advise! Can you provide the configuration file for self-training? Thank you very much!

**Comment by Siyuan-Zhou** [comment]
@vickyFox The configuration file for self-training can now be found in the ./configs directory.
