### ISSUE TITLE
Is it correct for D_gp maintaining [nan] in training period?

### ISSUE THREAD

**Issue by Zealoe** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#14]
In Pascal VOC training period, the value of D_gp is always [nan]. Is it correct? Thanks!

**Comment by Siyuan-Zhou** [comment]
@Zealoe Yes, it is correct. D_gp is not nan when the adversarial loss type is 'wgan_gp' in the config file. Actually, we never use 'wgan_gp', so D_gp remains [nan].
