### ISSUE TITLE
BaiDuYun is bad!!! Google Drive is good!!!

### ISSUE THREAD

**Issue by whitesockcat** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#2]
Can you share your file by another way?
Thx!!!

**Comment by Siyuan-Zhou** [comment]
@whitesockcat Thanks for your great advice! We are now providing two channels to download files: BCMI-Cloud and BaiduNetDisk. You can find both of them in our README now. If you think BaiduNetDisk is not good, you may choose BCMI-Cloud instead.

**Comment by whitesockcat** [comment]
thank you !!!!!!!!!!
