### ISSUE TITLE
Train and val data path

### ISSUE THREAD

**Issue by andygong2018** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#3]
I download the data follow the installation 3, using 'CaGNet_VOC2012_data.tar'. In train.py line 166, I print the train and val data:
![微信截图_20200911102303](https://user-images.githubusercontent.com/36817459/92844779-cfbec580-f418-11ea-882e-63cd3cc881b2.png)
and the print results are:
![微信截图_20200911102359](https://user-images.githubusercontent.com/36817459/92844890-ee24c100-f418-11ea-91e0-0c32cd564223.png)
the datapath is '/home/schoudhu/zss/SBD/dataset/', how can I change the path to mine?
Thanks

**Comment by zhangxgu** [comment]
@andygong2018 
Hi, there is no need to change the path. We only use the name of the corresponding data. 
You can run the code by simply changing the path of VOC in the config file.

**Comment by andygong2018** [comment]
> @andygong2018
> Hi, there is no need to change the path. We only use the name of the corresponding data.
> You can run the code by simply changing the path of VOC in the config file.

Thanks a lot!
Yes, I have found the corresponding in the method set_files.

**Comment by andygong2018** [comment]
In addition, in your VOC train_list, there are 10582 images, and it contains seen_cls and novel_cls 20 classes. So, in the train loop, if the train_data contains 20 classes or 15 seen_cls?
Thanks!
