### ISSUE TITLE
Train classes problem

### ISSUE THREAD

**Issue by andygong2018** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#4]
In your VOC train_list, there is 10582 images, I find it contains the 15 seen_cls and 5 novel_cls.
So, in the train loop, do you use all the 20 classes or only 15 seen_cls?
Thanks!

**Comment by Siyuan-Zhou** [comment]
@andygong2018 Thanks for your question. In the training loop of VOC, we only use annotations of 15 seen classes. When we deal with train images, we may encounter pixels that may not belong to these 15 seen classes, in which case we mark the labels of these pixels as 'ignored'.

**Comment by andygong2018** [comment]
> @andygong2018 Thanks for your question. In the training loop of VOC, we only use annotations of 15 seen classes. When we deal with train images, we may encounter pixels that may not belong to these 15 seen classes, in which case we mark the labels of these pixels as 'ignored'.

Thanks！
