### ISSUE TITLE
How to train custom data

### ISSUE THREAD

**Issue by qybing** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#5]
How to train custom data？or
In the folder, 'dataset/voc12' , how to generate the file  .npy and .pkl

**Comment by Siyuan-Zhou** [comment]
@qybing We will describe how to train custom data in 'README.md' in a few days.

**Comment by qybing** [comment]
@Siyuan-Zhou  In the folder, 'dataset/voc12' , how to generate the file .npy and .pkl?

**Comment by qybing** [comment]
@Siyuan-Zhou Thanks a lot,In the folder, 'dataset/voc12' , how to generate the file .npy and .pkl?

**Comment by qybing** [comment]
@Siyuan-Zhou Can you write prediction code？
