### ISSUE TITLE
How to Visualization on Pascal-VOC

### ISSUE THREAD

**Issue by qybing** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#7]
Use your pretrained weight,how to Visualization on Pascal-VOC. Can you write a demo？

**Comment by qybing** [comment]
@Siyuan-Zhou Can you write prediction code？

**Comment by zhangxgu** [comment]
@qybing the predcition code will be release after a few weeks because we are now working hard on a deadline.
