### ISSUE TITLE
can you tell me that how many iters it takes before Mean Acc of Unseen is not zero?

### ISSUE THREAD

**Issue by greathope** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#8]

**Comment by Siyuan-Zhou** [comment]
@greathope In the training phase, the Mean Acc of Unseen maintains zero, but it will not be zero as soon as you perform the finetuning stage. To be specific, it may takes 100-200 iters for the Mean Acc of Unseen to be not zero during finetuning.

**Comment by greathope** [comment]
@Siyuan-Zhou thanks. another question, It occurs error: out of memory when I perform the finetuning stage, my  gpu card is v100 32g, how can I fix this?

**Comment by Siyuan-Zhou** [comment]
@greathope In directory './configs', you can set config['IMAGE']['SIZE']['TRAIN'] or config['BATCH_SIZE']['TRAIN'] smaller in the corresponding config file that you use. By the way, the larger the total of categories is, the larger space the classifier in our CaGNet will use.
