### ISSUE TITLE
Generate word vector

### ISSUE THREAD

**Issue by dwangxxx** [bcmi/CaGNet-Zero-Shot-Semantic-Segmentation#9]
Hello, I want to train my own dataset, how can I generate the word vector? Can you give me some reference? Thank you very much!!!

**Comment by zhangxgu** [comment]
Hi, @dwangxxx , you can obtain the word vectors by searching the label names in other pretrained wordvector metrix like word2vec, glove, fasttext and so on.

**Comment by dwangxxx** [comment]
> Hi, @dwangxxx , you can obtain the word vectors by searching the label names in other pretrained wordvector metrix like word2vec, glove, fasttext and so on.

OK, Thank you!
